// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.Features.Payments
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreatePaymentMethodsFeature : object, Xunit.IClassFixture<CreatePaymentMethodsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreatePaymentMethods.feature"
#line hidden
        
        public CreatePaymentMethodsFeature(CreatePaymentMethodsFeature.FixtureData fixtureData, DuxCommerce_Specifications_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Payments", "Create Payment Methods", "\tIn order to receive payment from my customers\r\n\tAs a store admin\r\n\tI want to add" +
                    " payment methods to my store", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create payment methods - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Payment Methods")]
        [Xunit.TraitAttribute("Description", "Create payment methods - green path")]
        [Xunit.InlineDataAttribute("Cash on Delivery", "CashOnDelivery", "Details1", "Instruction1", new string[0])]
        [Xunit.InlineDataAttribute("Bank Deposit", "BankDeposit", "Details2", "Instruction2", new string[0])]
        [Xunit.InlineDataAttribute("Money Order", "MoneyOrder", "Details3", "Instruction3", new string[0])]
        public virtual void CreatePaymentMethods_GreenPath(string name, string type, string additionalDetails, string paymentInstructions, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Type", type);
            argumentsOfScenario.Add("AdditionalDetails", additionalDetails);
            argumentsOfScenario.Add("PaymentInstructions", paymentInstructions);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create payment methods - green path", null, tagsOfScenario, argumentsOfScenario);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Type",
                            "AdditionalDetails",
                            "PaymentInstructions"});
                table19.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", type),
                            string.Format("{0}", additionalDetails),
                            string.Format("{0}", paymentInstructions)});
#line 7
 testRunner.Given("Tom enters the following payment method information:", ((string)(null)), table19, "Given ");
#line hidden
#line 10
 testRunner.When("Tome saves the payment method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
 testRunner.And("payment method should be created as expected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create payment methods - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Payment Methods")]
        [Xunit.TraitAttribute("Description", "Create payment methods - red path")]
        [Xunit.InlineDataAttribute("Cash on Delivery", "Cash On Delivery", "Details1", "Instruction1", "Invalid method type", new string[0])]
        [Xunit.InlineDataAttribute("Bank Deposit", "Bank Deposit", "Details2", "Instruction2", "Invalid method type", new string[0])]
        [Xunit.InlineDataAttribute("Money Order", "Money Order", "Details3", "Instruction3", "Invalid method type", new string[0])]
        [Xunit.InlineDataAttribute("Payment method name that is more than 50 characters", "MoneyOrder", "Details3", "Instruction3", "Method name exceeds 50 characters", new string[0])]
        public virtual void CreatePaymentMethods_RedPath(string name, string type, string additionalDetails, string paymentInstructions, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Type", type);
            argumentsOfScenario.Add("AdditionalDetails", additionalDetails);
            argumentsOfScenario.Add("PaymentInstructions", paymentInstructions);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create payment methods - red path", null, tagsOfScenario, argumentsOfScenario);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Type",
                            "AdditionalDetails",
                            "PaymentInstructions"});
                table20.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", type),
                            string.Format("{0}", additionalDetails),
                            string.Format("{0}", paymentInstructions)});
#line 20
 testRunner.Given("Tom enters the following payment method information:", ((string)(null)), table20, "Given ");
#line hidden
#line 23
 testRunner.When("Tome saves the payment method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreatePaymentMethodsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreatePaymentMethodsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
