// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateShippingProfileFeature : object, Xunit.IClassFixture<CreateShippingProfileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateShippingProfiles.feature"
#line hidden
        
        public CreateShippingProfileFeature(CreateShippingProfileFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Create Shipping Profile", "\tIn order to customize my online store\r\n\tAs a store admin\r\n\tI want to save my sto" +
                    "re profile", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create default shipping profile")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Shipping Profile")]
        [Xunit.TraitAttribute("Description", "Create default shipping profile")]
        public virtual void CreateDefaultShippingProfile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create default shipping profile", null, tagsOfScenario, argumentsOfScenario);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table4.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            "MetricSystem",
                            "Gram",
                            "Centimeter"});
#line 7
 testRunner.Given("Tom enters the following store profile:", ((string)(null)), table4, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table5.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 10
 testRunner.And("Tome enters the following store address:", ((string)(null)), table5, "And ");
#line hidden
#line 13
 testRunner.When("Tom saves the store profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "IsDefault"});
                table6.AddRow(new string[] {
                            "Default Profile",
                            "True"});
#line 15
 testRunner.And("default shipping profile should be created as follow:", ((string)(null)), table6, "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode",
                            "IsDefault"});
                table7.AddRow(new string[] {
                            "1 Market Street",
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU",
                            "True"});
#line 18
 testRunner.And("shipping origin should be created as follow:", ((string)(null)), table7, "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table8.AddRow(new string[] {
                            "AU"});
#line 21
 testRunner.And("shipping zone should be created as follow:", ((string)(null)), table8, "And ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "CountryCode"});
                table9.AddRow(new string[] {
                            "AU"});
#line 24
 testRunner.And("shippig countries should be created as follow:", ((string)(null)), table9, "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "CountryCode",
                            "Name"});
                table10.AddRow(new string[] {
                            "AU",
                            "Australian Capital Territory"});
                table10.AddRow(new string[] {
                            "AU",
                            "New South Wales"});
                table10.AddRow(new string[] {
                            "AU",
                            "Northern Territory"});
                table10.AddRow(new string[] {
                            "AU",
                            "Queensland"});
                table10.AddRow(new string[] {
                            "AU",
                            "South Australia"});
                table10.AddRow(new string[] {
                            "AU",
                            "Tasmania"});
                table10.AddRow(new string[] {
                            "AU",
                            "Victoria"});
                table10.AddRow(new string[] {
                            "AU",
                            "Western Australia"});
#line 27
 testRunner.And("shippig states should be created as follow:", ((string)(null)), table10, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateShippingProfileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateShippingProfileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
