// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateShippingProfileFeature : object, Xunit.IClassFixture<CreateShippingProfileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateShippingProfile.feature"
#line hidden
        
        public CreateShippingProfileFeature(CreateShippingProfileFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Create Shipping Profile", "\tIn order to customize my online store\r\n\tAs a store admin\r\n\tI want to create my s" +
                    "hipping profile", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "OriginId",
                        "FirstName",
                        "LastName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "PostalCode",
                        "StateName",
                        "CountryCode"});
            table4.AddRow(new string[] {
                        "1",
                        "James",
                        "Harper",
                        "1 Market Street",
                        "",
                        "Sydney",
                        "2000",
                        "New South Wales",
                        "AU"});
#line 7
 testRunner.Given("Tom already created the following shipping origins:", ((string)(null)), table4, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create custom shipping profile")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Shipping Profile")]
        [Xunit.TraitAttribute("Description", "Create custom shipping profile")]
        [Xunit.InlineDataAttribute("ByWeight", "By Weight", new string[0])]
        [Xunit.InlineDataAttribute("ByQuantity", "By Quantity", new string[0])]
        [Xunit.InlineDataAttribute("ByOrderTotal", "By Order Total", new string[0])]
        public virtual void CreateCustomShippingProfile(string methodType, string methodName, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("MethodType", methodType);
            argumentsOfScenario.Add("MethodName", methodName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create custom shipping profile", null, tagsOfScenario, argumentsOfScenario);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 12
 testRunner.And("Tom enters shipping profile name Heavy Products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
 testRunner.And("Tom selects shipping origin 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And("Tom enters the zone name ANZ", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "CountryCode"});
                table5.AddRow(new string[] {
                            "AU"});
                table5.AddRow(new string[] {
                            "NZ"});
#line 15
 testRunner.And("Tom selects the following shipping countries:", ((string)(null)), table5, "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "CountryCode",
                            "Name"});
                table6.AddRow(new string[] {
                            "AU",
                            "New South Wales"});
                table6.AddRow(new string[] {
                            "AU",
                            "Queensland"});
                table6.AddRow(new string[] {
                            "NZ",
                            "Auckland"});
                table6.AddRow(new string[] {
                            "NZ",
                            "Wellington"});
#line 19
 testRunner.And("Tom selects the following shipping states:", ((string)(null)), table6, "And ");
#line hidden
#line 25
 testRunner.And(string.Format("Tom selects shipping method type {0} and enters method name {1}", methodType, methodName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Min",
                            "Max",
                            "Rate"});
                table7.AddRow(new string[] {
                            "0",
                            "100",
                            "50"});
                table7.AddRow(new string[] {
                            "100",
                            "200",
                            "100"});
                table7.AddRow(new string[] {
                            "200",
                            "40000",
                            "200"});
#line 26
 testRunner.And("Tome enters the following rates:", ((string)(null)), table7, "And ");
#line hidden
#line 31
 testRunner.When("Tom saves the shipping profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
 testRunner.And("custom shipping profile should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateShippingProfileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateShippingProfileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
