// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateAProductFeature : object, Xunit.IClassFixture<CreateAProductFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Product.feature"
#line hidden
        
        public CreateAProductFeature(CreateAProductFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Create a product", "\tIn order to sell products online\r\n\tAs a store admin\r\n\tI want to add proucts to m" +
                    "y store first", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create products - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create a product")]
        [Xunit.TraitAttribute("Description", "Create products - green path")]
        public virtual void CreateProducts_GreenPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create products - green path", null, tagsOfScenario, argumentsOfScenario);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table1.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "ShipSeparately",
                            "ddd-book",
                            "1234567890111",
                            "True",
                            "Remove"});
                table1.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "False",
                            "ContinueSelling"});
                table1.AddRow(new string[] {
                            "3",
                            "TDD",
                            "TDD Description",
                            "80",
                            "100",
                            "60",
                            "3",
                            "4",
                            "5",
                            "6",
                            "DigitalProduct",
                            "tdd-book",
                            "1234567890333",
                            "True",
                            "StopSelling"});
#line 7
 testRunner.Given("Tom enters the following product information:", ((string)(null)), table1, "Given ");
#line hidden
#line 12
 testRunner.When("Tom saves the products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table2.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "ShipSeparately",
                            "ddd-book",
                            "1234567890111",
                            "True",
                            "Remove"});
                table2.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "False",
                            "ContinueSelling"});
                table2.AddRow(new string[] {
                            "3",
                            "TDD",
                            "TDD Description",
                            "80",
                            "100",
                            "60",
                            "3",
                            "4",
                            "5",
                            "6",
                            "DigitalProduct",
                            "tdd-book",
                            "1234567890333",
                            "True",
                            "StopSelling"});
#line 14
 testRunner.And("the products should be created as follow:", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create products - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create a product")]
        [Xunit.TraitAttribute("Description", "Create products - red path")]
        public virtual void CreateProducts_RedPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create products - red path", null, tagsOfScenario, argumentsOfScenario);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule",
                            "Comment"});
                table3.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "Ship Separately",
                            "ddd-book",
                            "1234567890111",
                            "Yes",
                            "Remove",
                            "Invalid ShippingType"});
                table3.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "No",
                            "Continue Selling",
                            "Invalid OutOfStock Rule"});
#line 21
 testRunner.Given("Tom enters the following product information:", ((string)(null)), table3, "Given ");
#line hidden
#line 25
 testRunner.When("Tom saves the products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update products - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create a product")]
        [Xunit.TraitAttribute("Description", "Update products - green path")]
        public virtual void UpdateProducts_GreenPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update products - green path", null, tagsOfScenario, argumentsOfScenario);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table4.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "ShipSeparately",
                            "ddd-book",
                            "1234567890111",
                            "True",
                            "Remove"});
                table4.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "False",
                            "ContinueSelling"});
                table4.AddRow(new string[] {
                            "3",
                            "TDD",
                            "TDD Description",
                            "80",
                            "100",
                            "60",
                            "3",
                            "4",
                            "5",
                            "6",
                            "DigitalProduct",
                            "tdd-book",
                            "1234567890333",
                            "True",
                            "StopSelling"});
#line 29
 testRunner.Given("Tom already created the following products:", ((string)(null)), table4, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table5.AddRow(new string[] {
                            "1",
                            "DDD Lite",
                            "DDD Desc",
                            "90",
                            "110",
                            "70",
                            "4",
                            "3",
                            "2",
                            "1",
                            "DigitalProduct",
                            "ddd-lite",
                            "1234567890123",
                            "True",
                            "StopSelling"});
                table5.AddRow(new string[] {
                            "2",
                            "BDD Lite",
                            "BDD Desc",
                            "80",
                            "100",
                            "60",
                            "5",
                            "4",
                            "3",
                            "2",
                            "ShipSeparately",
                            "bdd-lite",
                            "1234567890234",
                            "True",
                            "Remove"});
                table5.AddRow(new string[] {
                            "3",
                            "TDD Lite",
                            "TDD Desc",
                            "70",
                            "90",
                            "50",
                            "6",
                            "5",
                            "4",
                            "3",
                            "PhysicalProduct",
                            "tdd-lite",
                            "1234567890345",
                            "False",
                            "ContinueSelling"});
#line 34
 testRunner.And("Tom enters the following product information:", ((string)(null)), table5, "And ");
#line hidden
#line 39
 testRunner.When("Tom updates the products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table6.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "ShipSeparately",
                            "ddd-book",
                            "1234567890111",
                            "True",
                            "Remove"});
                table6.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "False",
                            "ContinueSelling"});
                table6.AddRow(new string[] {
                            "3",
                            "TDD",
                            "TDD Description",
                            "80",
                            "100",
                            "60",
                            "3",
                            "4",
                            "5",
                            "6",
                            "DigitalProduct",
                            "tdd-book",
                            "1234567890333",
                            "True",
                            "StopSelling"});
#line 41
 testRunner.And("the products should be updated as follow:", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update products - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create a product")]
        [Xunit.TraitAttribute("Description", "Update products - red path")]
        public virtual void UpdateProducts_RedPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update products - red path", null, tagsOfScenario, argumentsOfScenario);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table7.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "ShipSeparately",
                            "ddd-book",
                            "1234567890111",
                            "True",
                            "Remove"});
                table7.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "False",
                            "ContinueSelling"});
#line 48
 testRunner.Given("Tom already created the following products:", ((string)(null)), table7, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule",
                            "Comment"});
                table8.AddRow(new string[] {
                            "1",
                            "DDD Lite",
                            "DDD Desc",
                            "90",
                            "110",
                            "70",
                            "4",
                            "3",
                            "2",
                            "1",
                            "DigitalProduct",
                            "ddd-lite",
                            "1234567890123",
                            "True",
                            "Stop Selling",
                            "Invalid OutOfStock Rule"});
                table8.AddRow(new string[] {
                            "2",
                            "BDD Lite",
                            "BDD Desc",
                            "80",
                            "100",
                            "60",
                            "5",
                            "4",
                            "3",
                            "2",
                            "Ship Separately",
                            "bdd-lite",
                            "1234567890234",
                            "True",
                            "Remove",
                            "Invalid ShippingType"});
#line 52
 testRunner.And("Tom enters the following product information:", ((string)(null)), table8, "And ");
#line hidden
#line 56
 testRunner.When("Tom updates the products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateAProductFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateAProductFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
