// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ShoppingCartFeature : object, Xunit.IClassFixture<ShoppingCartFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ShoppingCart.feature"
#line hidden
        
        public ShoppingCartFeature(ShoppingCartFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "ShoppingCart", "\tIn order to place an order\r\n\tAs a customer\r\n\tI want to add products to my shoppi" +
                    "ng cart", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Index",
                        "Name",
                        "Description",
                        "Price",
                        "Retail",
                        "Cost",
                        "Length",
                        "Width",
                        "Height",
                        "Weight",
                        "ProductType",
                        "Sku",
                        "Barcode",
                        "TrackInventory",
                        "OutOfStockRule"});
            table11.AddRow(new string[] {
                        "1",
                        "DDD",
                        "DDD Description",
                        "100",
                        "120",
                        "80",
                        "1",
                        "2",
                        "3",
                        "4",
                        "DigitalProduct",
                        "ddd-book",
                        "1234567890111",
                        "True",
                        "Remove"});
            table11.AddRow(new string[] {
                        "2",
                        "BDD",
                        "BDD Description",
                        "50",
                        "110",
                        "70",
                        "2",
                        "3",
                        "4",
                        "5",
                        "PhysicalProduct",
                        "bdd-book",
                        "1234567890222",
                        "False",
                        "ContinueSelling"});
            table11.AddRow(new string[] {
                        "3",
                        "TDD",
                        "TDD Description",
                        "80",
                        "100",
                        "60",
                        "3",
                        "4",
                        "5",
                        "6",
                        "DigitalProduct",
                        "tdd-book",
                        "1234567890333",
                        "True",
                        "StopSelling"});
#line 7
 testRunner.Given("the following products are already created:", ((string)(null)), table11, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add to cart")]
        [Xunit.TraitAttribute("FeatureTitle", "ShoppingCart")]
        [Xunit.TraitAttribute("Description", "Add to cart")]
        public virtual void AddToCart()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add to cart", null, tagsOfScenario, argumentsOfScenario);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Quantity"});
                table12.AddRow(new string[] {
                            "1",
                            "DDD",
                            "1"});
                table12.AddRow(new string[] {
                            "1",
                            "DDD",
                            "2"});
                table12.AddRow(new string[] {
                            "2",
                            "BDD",
                            "8"});
#line 14
 testRunner.When("Amy adds the following products to her shopping cart:", ((string)(null)), table12, "When ");
#line hidden
#line 19
 testRunner.Then("Amy should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Price",
                            "Quantity",
                            "ItemTotal"});
                table13.AddRow(new string[] {
                            "1",
                            "DDD",
                            "100",
                            "3",
                            "300"});
                table13.AddRow(new string[] {
                            "2",
                            "BDD",
                            "50",
                            "8",
                            "400"});
#line 20
 testRunner.And("her cart details should look as follow:", ((string)(null)), table13, "And ");
#line hidden
#line 24
 testRunner.And("the cart total is $700", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update cart")]
        [Xunit.TraitAttribute("FeatureTitle", "ShoppingCart")]
        [Xunit.TraitAttribute("Description", "Update cart")]
        public virtual void UpdateCart()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update cart", null, tagsOfScenario, argumentsOfScenario);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Quantity"});
                table14.AddRow(new string[] {
                            "1",
                            "DDD",
                            "4"});
                table14.AddRow(new string[] {
                            "2",
                            "BDD",
                            "8"});
#line 27
 testRunner.And("Amy adds the following products to her shopping cart:", ((string)(null)), table14, "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Quantity"});
                table15.AddRow(new string[] {
                            "1",
                            "DDD",
                            "10"});
                table15.AddRow(new string[] {
                            "2",
                            "BDD",
                            "20"});
#line 31
 testRunner.When("Amy updates her shopping cart as follow:", ((string)(null)), table15, "When ");
#line hidden
#line 35
 testRunner.Then("Amy should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Price",
                            "Quantity",
                            "ItemTotal"});
                table16.AddRow(new string[] {
                            "1",
                            "DDD",
                            "100",
                            "10",
                            "1000"});
                table16.AddRow(new string[] {
                            "2",
                            "BDD",
                            "50",
                            "20",
                            "1000"});
#line 36
 testRunner.And("her cart details should look as follow:", ((string)(null)), table16, "And ");
#line hidden
#line 40
 testRunner.And("the cart total is $2000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Delete cart item")]
        [Xunit.TraitAttribute("FeatureTitle", "ShoppingCart")]
        [Xunit.TraitAttribute("Description", "Delete cart item")]
        public virtual void DeleteCartItem()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete cart item", null, tagsOfScenario, argumentsOfScenario);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Quantity"});
                table17.AddRow(new string[] {
                            "1",
                            "DDD",
                            "2"});
                table17.AddRow(new string[] {
                            "2",
                            "BDD",
                            "4"});
                table17.AddRow(new string[] {
                            "3",
                            "TDD",
                            "6"});
#line 43
 testRunner.And("Amy adds the following products to her shopping cart:", ((string)(null)), table17, "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name"});
                table18.AddRow(new string[] {
                            "1",
                            "DDD"});
                table18.AddRow(new string[] {
                            "3",
                            "TDD"});
#line 48
 testRunner.When("Amy deletes the following cart items:", ((string)(null)), table18, "When ");
#line hidden
#line 52
 testRunner.Then("Amy should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Price",
                            "Quantity",
                            "ItemTotal"});
                table19.AddRow(new string[] {
                            "2",
                            "BDD",
                            "50",
                            "4",
                            "200"});
#line 53
 testRunner.And("her cart details should look as follow:", ((string)(null)), table19, "And ");
#line hidden
#line 56
 testRunner.And("the cart total is $200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ShoppingCartFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ShoppingCartFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
