// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateStoreDetailsFeature : object, Xunit.IClassFixture<CreateStoreDetailsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "StoreDetails.feature"
#line hidden
        
        public CreateStoreDetailsFeature(CreateStoreDetailsFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Create Store Details", "\tIn order to customize my online store\r\n\tAs a store admin\r\n\tI want to update my s" +
                    "tore details", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create store details - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Store Details")]
        [Xunit.TraitAttribute("Description", "Create store details - green path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Gram", "Centimeter", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Meter", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Foot", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Ounce", "Inch", new string[0])]
        public virtual void CreateStoreDetails_GreenPath(string unitSystem, string weightUnit, string lengthUnit, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create store details - green path", null, tagsOfScenario, argumentsOfScenario);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table13.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 7
 testRunner.Given("Tom enters the following store details:", ((string)(null)), table13, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Address1",
                            "Address2",
                            "Address3",
                            "City",
                            "PostalCode",
                            "State",
                            "Country"});
                table14.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 10
 testRunner.And("Tome enters the following store address:", ((string)(null)), table14, "And ");
#line hidden
#line 13
 testRunner.When("Tom saves the store details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create store details - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Store Details")]
        [Xunit.TraitAttribute("Description", "Create store details - red path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Foot", "Invalid LengthUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Kilogram", "Inch", "Invalid LengthUnit", new string[0])]
        public virtual void CreateStoreDetails_RedPath(string unitSystem, string weightUnit, string lengthUnit, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create store details - red path", null, tagsOfScenario, argumentsOfScenario);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table15.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 23
 testRunner.Given("Tom enters the following store details:", ((string)(null)), table15, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Address1",
                            "Address2",
                            "Address3",
                            "City",
                            "PostalCode",
                            "State",
                            "Country"});
                table16.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 26
 testRunner.And("Tome enters the following store address:", ((string)(null)), table16, "And ");
#line hidden
#line 29
 testRunner.When("Tom saves the store details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateStoreDetailsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateStoreDetailsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
