// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UpdateStoreDetailsFeature : object, Xunit.IClassFixture<UpdateStoreDetailsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateStoreDetails.feature"
#line hidden
        
        public UpdateStoreDetailsFeature(UpdateStoreDetailsFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Update Store Details", "\tIn order to customize my online store\r\n\tAs a store admin\r\n\tI want to update my s" +
                    "tore details", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "StoreName",
                        "ContactEmail",
                        "SenderEmail",
                        "BusinessName",
                        "PhoneNumber",
                        "TimeZoneId",
                        "UnitSystem",
                        "WeightUnit",
                        "LengthUnit"});
            table23.AddRow(new string[] {
                        "Deals365",
                        "c@gmail.com",
                        "s@gmail.com",
                        "Deals365 PTY",
                        "89457621",
                        "UTC",
                        "MetricSystem",
                        "Gram",
                        "Centimeter"});
#line 7
 testRunner.Given("Tom already created the following store details:", ((string)(null)), table23, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Address1",
                        "Address2",
                        "Address3",
                        "City",
                        "PostalCode",
                        "State",
                        "Country"});
            table24.AddRow(new string[] {
                        "1 Market Street",
                        "",
                        "",
                        "Sydney",
                        "2000",
                        "New South Wales",
                        "AU"});
#line 10
 testRunner.And("Tom already created the following store address:", ((string)(null)), table24, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update store details - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update Store Details")]
        [Xunit.TraitAttribute("Description", "Update store details - green path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Meter", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Foot", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Ounce", "Inch", new string[0])]
        public virtual void UpdateStoreDetails_GreenPath(string unitSystem, string weightUnit, string lengthUnit, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update store details - green path", null, tagsOfScenario, argumentsOfScenario);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table25.AddRow(new string[] {
                            "Deals360",
                            "contact@gmail.com",
                            "sender@gmail.com",
                            "Deals360 PTY",
                            "89457688",
                            "UTC+2",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 15
 testRunner.And("Tom enters the following store details:", ((string)(null)), table25, "And ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Address1",
                            "Address2",
                            "Address3",
                            "City",
                            "PostalCode",
                            "State",
                            "Country"});
                table26.AddRow(new string[] {
                            "Unit 7",
                            "2 Market Street",
                            "",
                            "Melbourne",
                            "3000",
                            "Victoria",
                            "AU"});
#line 18
 testRunner.And("Tome enters the following store address:", ((string)(null)), table26, "And ");
#line hidden
#line 21
 testRunner.When("Tom updates the store details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table27.AddRow(new string[] {
                            "Deals360",
                            "contact@gmail.com",
                            "sender@gmail.com",
                            "Deals360 PTY",
                            "89457688",
                            "UTC+2",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 23
 testRunner.And("the store details should be created as follow:", ((string)(null)), table27, "And ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Address1",
                            "Address2",
                            "Address3",
                            "City",
                            "PostalCode",
                            "State",
                            "Country"});
                table28.AddRow(new string[] {
                            "Unit 7",
                            "2 Market Street",
                            "",
                            "Melbourne",
                            "3000",
                            "Victoria",
                            "AU"});
#line 26
 testRunner.And("the store address should be created as follow:", ((string)(null)), table28, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update store details - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update Store Details")]
        [Xunit.TraitAttribute("Description", "Update store details - red path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Foot", "Invalid LengthUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Kilogram", "Inch", "Invalid LengthUnit", new string[0])]
        public virtual void UpdateStoreDetails_RedPath(string unitSystem, string weightUnit, string lengthUnit, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update store details - red path", null, tagsOfScenario, argumentsOfScenario);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table29.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 36
 testRunner.And("Tom enters the following store details:", ((string)(null)), table29, "And ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Address1",
                            "Address2",
                            "Address3",
                            "City",
                            "PostalCode",
                            "State",
                            "Country"});
                table30.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 39
 testRunner.And("Tome enters the following store address:", ((string)(null)), table30, "And ");
#line hidden
#line 42
 testRunner.When("Tom updates the store details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 43
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UpdateStoreDetailsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UpdateStoreDetailsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
