// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.UseCases.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UpdateAProductFeature : object, Xunit.IClassFixture<UpdateAProductFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateProduct.feature"
#line hidden
        
        public UpdateAProductFeature(UpdateAProductFeature.FixtureData fixtureData, DuxCommerce_Specifications_UseCases_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Update a product", "\tIn order to keep the product info up to date\r\n\tAs a store admin\r\n\tI want to upda" +
                    "te the proucts", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Index",
                        "Name",
                        "Description",
                        "Price",
                        "Retail",
                        "Cost",
                        "Length",
                        "Width",
                        "Height",
                        "Weight",
                        "ShippingType",
                        "Sku",
                        "Barcode",
                        "TrackInventory",
                        "OutOfStockRule"});
            table19.AddRow(new string[] {
                        "1",
                        "DDD",
                        "DDD Description",
                        "100",
                        "120",
                        "80",
                        "1",
                        "2",
                        "3",
                        "4",
                        "ShipSeparately",
                        "ddd-book",
                        "1234567890111",
                        "True",
                        "Remove"});
            table19.AddRow(new string[] {
                        "2",
                        "BDD",
                        "BDD Description",
                        "90",
                        "110",
                        "70",
                        "2",
                        "3",
                        "4",
                        "5",
                        "PhysicalProduct",
                        "bdd-book",
                        "1234567890222",
                        "False",
                        "ContinueSelling"});
            table19.AddRow(new string[] {
                        "3",
                        "TDD",
                        "TDD Description",
                        "80",
                        "100",
                        "60",
                        "3",
                        "4",
                        "5",
                        "6",
                        "DigitalProduct",
                        "tdd-book",
                        "1234567890333",
                        "True",
                        "StopSelling"});
#line 7
 testRunner.Given("Tom already created the following products:", ((string)(null)), table19, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update products - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update a product")]
        [Xunit.TraitAttribute("Description", "Update products - green path")]
        public virtual void UpdateProducts_GreenPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update products - green path", null, tagsOfScenario, argumentsOfScenario);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table20.AddRow(new string[] {
                            "1",
                            "DDD Lite",
                            "DDD Desc",
                            "90",
                            "110",
                            "70",
                            "4",
                            "3",
                            "2",
                            "1",
                            "DigitalProduct",
                            "ddd-lite",
                            "1234567890123",
                            "True",
                            "StopSelling"});
                table20.AddRow(new string[] {
                            "2",
                            "BDD Lite",
                            "BDD Desc",
                            "80",
                            "100",
                            "60",
                            "5",
                            "4",
                            "3",
                            "2",
                            "ShipSeparately",
                            "bdd-lite",
                            "1234567890234",
                            "True",
                            "Remove"});
                table20.AddRow(new string[] {
                            "3",
                            "TDD Lite",
                            "TDD Desc",
                            "70",
                            "90",
                            "50",
                            "6",
                            "5",
                            "4",
                            "3",
                            "PhysicalProduct",
                            "tdd-lite",
                            "1234567890345",
                            "False",
                            "ContinueSelling"});
#line 14
 testRunner.And("Tom enters the following product information:", ((string)(null)), table20, "And ");
#line hidden
#line 19
 testRunner.When("Tom updates the products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table21.AddRow(new string[] {
                            "1",
                            "DDD",
                            "DDD Description",
                            "100",
                            "120",
                            "80",
                            "1",
                            "2",
                            "3",
                            "4",
                            "ShipSeparately",
                            "ddd-book",
                            "1234567890111",
                            "True",
                            "Remove"});
                table21.AddRow(new string[] {
                            "2",
                            "BDD",
                            "BDD Description",
                            "90",
                            "110",
                            "70",
                            "2",
                            "3",
                            "4",
                            "5",
                            "PhysicalProduct",
                            "bdd-book",
                            "1234567890222",
                            "False",
                            "ContinueSelling"});
                table21.AddRow(new string[] {
                            "3",
                            "TDD",
                            "TDD Description",
                            "80",
                            "100",
                            "60",
                            "3",
                            "4",
                            "5",
                            "6",
                            "DigitalProduct",
                            "tdd-book",
                            "1234567890333",
                            "True",
                            "StopSelling"});
#line 21
 testRunner.And("the products should be updated as follow:", ((string)(null)), table21, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update products - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update a product")]
        [Xunit.TraitAttribute("Description", "Update products - red path")]
        public virtual void UpdateProducts_RedPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update products - red path", null, tagsOfScenario, argumentsOfScenario);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Index",
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ShippingType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule",
                            "Comment"});
                table22.AddRow(new string[] {
                            "1",
                            "DDD Lite",
                            "DDD Desc",
                            "90",
                            "110",
                            "70",
                            "4",
                            "3",
                            "2",
                            "1",
                            "DigitalProduct",
                            "ddd-lite",
                            "1234567890123",
                            "True",
                            "Stop Selling",
                            "Invalid OutOfStock Rule"});
                table22.AddRow(new string[] {
                            "2",
                            "BDD Lite",
                            "BDD Desc",
                            "80",
                            "100",
                            "60",
                            "5",
                            "4",
                            "3",
                            "2",
                            "Ship Separately",
                            "bdd-lite",
                            "1234567890234",
                            "True",
                            "Remove",
                            "Invalid ShippingType"});
#line 28
 testRunner.And("Tom enters the following product information:", ((string)(null)), table22, "And ");
#line hidden
#line 32
 testRunner.When("Tom updates the products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UpdateAProductFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UpdateAProductFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
