// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.Features.Catalogue
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateProductsFeature : object, Xunit.IClassFixture<CreateProductsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateProducts.feature"
#line hidden
        
        public CreateProductsFeature(CreateProductsFeature.FixtureData fixtureData, DuxCommerce_Specifications_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Catalogue", "Create Products", "In order to sell products online\r\nAs a store admin\r\nI want to add proucts to my s" +
                    "tore first", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create products - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Products")]
        [Xunit.TraitAttribute("Description", "Create products - green path")]
        [Xunit.InlineDataAttribute("BDD", "BDD Description", "90", "110", "70", "2", "3", "4", "5", "PhysicalProduct", "bdd-book", "1234567890222", "False", "ContinueSelling", new string[0])]
        [Xunit.InlineDataAttribute("TDD", "TDD Description", "80", "100", "60", "3", "4", "5", "6", "DigitalProduct", "tdd-book", "1234567890333", "True", "StopSelling", new string[0])]
        public virtual void CreateProducts_GreenPath(string name, string description, string price, string retail, string cost, string length, string width, string height, string weight, string productType, string sku, string barcode, string trackInventory, string outOfStockRule, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("Price", price);
            argumentsOfScenario.Add("Retail", retail);
            argumentsOfScenario.Add("Cost", cost);
            argumentsOfScenario.Add("Length", length);
            argumentsOfScenario.Add("Width", width);
            argumentsOfScenario.Add("Height", height);
            argumentsOfScenario.Add("Weight", weight);
            argumentsOfScenario.Add("ProductType", productType);
            argumentsOfScenario.Add("Sku", sku);
            argumentsOfScenario.Add("Barcode", barcode);
            argumentsOfScenario.Add("TrackInventory", trackInventory);
            argumentsOfScenario.Add("OutOfStockRule", outOfStockRule);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create products - green path", null, tagsOfScenario, argumentsOfScenario);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ProductType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table1.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", description),
                            string.Format("{0}", price),
                            string.Format("{0}", retail),
                            string.Format("{0}", cost),
                            string.Format("{0}", length),
                            string.Format("{0}", width),
                            string.Format("{0}", height),
                            "<Weigth>",
                            string.Format("{0}", productType),
                            string.Format("{0}", sku),
                            string.Format("{0}", barcode),
                            string.Format("{0}", trackInventory),
                            string.Format("{0}", outOfStockRule)});
#line 7
        testRunner.Given("Tom updates the following product:", ((string)(null)), table1, "Given ");
#line hidden
#line 10
        testRunner.When("Tom saves the product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
        testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ProductType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table2.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", description),
                            string.Format("{0}", price),
                            string.Format("{0}", retail),
                            string.Format("{0}", cost),
                            string.Format("{0}", length),
                            string.Format("{0}", width),
                            string.Format("{0}", height),
                            "<Weigth>",
                            string.Format("{0}", productType),
                            string.Format("{0}", sku),
                            string.Format("{0}", barcode),
                            string.Format("{0}", trackInventory),
                            string.Format("{0}", outOfStockRule)});
#line 12
        testRunner.And("the product should be created as follow:", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create products - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Products")]
        [Xunit.TraitAttribute("Description", "Create products - red path")]
        [Xunit.InlineDataAttribute("DDD", "DDD Description", "100", "120", "80", "1", "2", "3", "4", "Physical Product", "ddd-book", "1234567890111", "Yes", "Remove", "Invalid Product Type", new string[0])]
        [Xunit.InlineDataAttribute("BDD", "BDD Description", "90", "110", "70", "2", "3", "4", "5", "PhysicalProduct", "bdd-book", "1234567890222", "No", "Continue Selling", "Invalid OutOfStock Rule", new string[0])]
        public virtual void CreateProducts_RedPath(
                    string name, 
                    string description, 
                    string price, 
                    string retail, 
                    string cost, 
                    string length, 
                    string width, 
                    string height, 
                    string weight, 
                    string productType, 
                    string sku, 
                    string barcode, 
                    string trackInventory, 
                    string outOfStockRule, 
                    string comment, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("Price", price);
            argumentsOfScenario.Add("Retail", retail);
            argumentsOfScenario.Add("Cost", cost);
            argumentsOfScenario.Add("Length", length);
            argumentsOfScenario.Add("Width", width);
            argumentsOfScenario.Add("Height", height);
            argumentsOfScenario.Add("Weight", weight);
            argumentsOfScenario.Add("ProductType", productType);
            argumentsOfScenario.Add("Sku", sku);
            argumentsOfScenario.Add("Barcode", barcode);
            argumentsOfScenario.Add("TrackInventory", trackInventory);
            argumentsOfScenario.Add("OutOfStockRule", outOfStockRule);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create products - red path", null, tagsOfScenario, argumentsOfScenario);
#line 21
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ProductType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table3.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", description),
                            string.Format("{0}", price),
                            string.Format("{0}", retail),
                            string.Format("{0}", cost),
                            string.Format("{0}", length),
                            string.Format("{0}", width),
                            string.Format("{0}", height),
                            "<Weigth>",
                            string.Format("{0}", productType),
                            string.Format("{0}", sku),
                            string.Format("{0}", barcode),
                            string.Format("{0}", trackInventory),
                            string.Format("{0}", outOfStockRule)});
#line 22
        testRunner.Given("Tom updates the following product:", ((string)(null)), table3, "Given ");
#line hidden
#line 25
        testRunner.When("Tom saves the product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
        testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateProductsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateProductsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
