// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.Features.Catalogue
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UpdateProductsFeature : object, Xunit.IClassFixture<UpdateProductsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateProducts.feature"
#line hidden
        
        public UpdateProductsFeature(UpdateProductsFeature.FixtureData fixtureData, DuxCommerce_Specifications_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Catalogue", "Update Products", "In order to keep the product info up to date\r\nAs a store admin\r\nI want to update " +
                    "the proucts", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Price",
                        "Retail",
                        "Cost",
                        "Length",
                        "Width",
                        "Height",
                        "Weight",
                        "ProductType",
                        "Sku",
                        "Barcode",
                        "TrackInventory",
                        "OutOfStockRule"});
            table4.AddRow(new string[] {
                        "DDD",
                        "DDD Description",
                        "100",
                        "120",
                        "80",
                        "1",
                        "2",
                        "3",
                        "4",
                        "DigitalProduct",
                        "ddd-book",
                        "1234567890111",
                        "True",
                        "Remove"});
#line 7
        testRunner.Given("Tom creates the following product:", ((string)(null)), table4, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update products - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update Products")]
        [Xunit.TraitAttribute("Description", "Update products - green path")]
        [Xunit.InlineDataAttribute("DDD Lite", "DDD Desc", "90", "110", "70", "4", "3", "2", "1", "DigitalProduct", "ddd-lite", "1234567890123", "True", "StopSelling", new string[0])]
        [Xunit.InlineDataAttribute("TDD Lite", "TDD Desc", "70", "90", "50", "6", "5", "4", "3", "PhysicalProduct", "tdd-lite", "1234567890345", "False", "ContinueSelling", new string[0])]
        public virtual void UpdateProducts_GreenPath(string name, string description, string price, string retail, string cost, string length, string width, string height, string weight, string productType, string sku, string barcode, string trackInventory, string outOfStockRule, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("Price", price);
            argumentsOfScenario.Add("Retail", retail);
            argumentsOfScenario.Add("Cost", cost);
            argumentsOfScenario.Add("Length", length);
            argumentsOfScenario.Add("Width", width);
            argumentsOfScenario.Add("Height", height);
            argumentsOfScenario.Add("Weight", weight);
            argumentsOfScenario.Add("ProductType", productType);
            argumentsOfScenario.Add("Sku", sku);
            argumentsOfScenario.Add("Barcode", barcode);
            argumentsOfScenario.Add("TrackInventory", trackInventory);
            argumentsOfScenario.Add("OutOfStockRule", outOfStockRule);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update products - green path", null, tagsOfScenario, argumentsOfScenario);
#line 11
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ProductType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table5.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", description),
                            string.Format("{0}", price),
                            string.Format("{0}", retail),
                            string.Format("{0}", cost),
                            string.Format("{0}", length),
                            string.Format("{0}", width),
                            string.Format("{0}", height),
                            string.Format("{0}", weight),
                            string.Format("{0}", productType),
                            string.Format("{0}", sku),
                            string.Format("{0}", barcode),
                            string.Format("{0}", trackInventory),
                            string.Format("{0}", outOfStockRule)});
#line 12
        testRunner.Given("Tom updates the following product:", ((string)(null)), table5, "Given ");
#line hidden
#line 15
        testRunner.When("Tom saves the updated product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
        testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ProductType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table6.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", description),
                            string.Format("{0}", price),
                            string.Format("{0}", retail),
                            string.Format("{0}", cost),
                            string.Format("{0}", length),
                            string.Format("{0}", width),
                            string.Format("{0}", height),
                            string.Format("{0}", weight),
                            string.Format("{0}", productType),
                            string.Format("{0}", sku),
                            string.Format("{0}", barcode),
                            string.Format("{0}", trackInventory),
                            string.Format("{0}", outOfStockRule)});
#line 17
        testRunner.And("the product should be updated as follow:", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update products - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update Products")]
        [Xunit.TraitAttribute("Description", "Update products - red path")]
        [Xunit.InlineDataAttribute("DDD Lite", "DDD Desc", "90", "110", "70", "4", "3", "2", "1", "DigitalProduct", "ddd-lite", "1234567890123", "True", "Stop Selling", "Invalid OutOfStock Rule", new string[0])]
        [Xunit.InlineDataAttribute("BDD Lite", "BDD Desc", "80", "100", "60", "5", "4", "3", "2", "Digital Product", "bdd-lite", "1234567890234", "True", "Remove", "Invalid ProductType", new string[0])]
        public virtual void UpdateProducts_RedPath(
                    string name, 
                    string description, 
                    string price, 
                    string retail, 
                    string cost, 
                    string length, 
                    string width, 
                    string height, 
                    string weight, 
                    string productType, 
                    string sku, 
                    string barcode, 
                    string trackInventory, 
                    string outOfStockRule, 
                    string comment, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("Price", price);
            argumentsOfScenario.Add("Retail", retail);
            argumentsOfScenario.Add("Cost", cost);
            argumentsOfScenario.Add("Length", length);
            argumentsOfScenario.Add("Width", width);
            argumentsOfScenario.Add("Height", height);
            argumentsOfScenario.Add("Weight", weight);
            argumentsOfScenario.Add("ProductType", productType);
            argumentsOfScenario.Add("Sku", sku);
            argumentsOfScenario.Add("Barcode", barcode);
            argumentsOfScenario.Add("TrackInventory", trackInventory);
            argumentsOfScenario.Add("OutOfStockRule", outOfStockRule);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update products - red path", null, tagsOfScenario, argumentsOfScenario);
#line 26
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Description",
                            "Price",
                            "Retail",
                            "Cost",
                            "Length",
                            "Width",
                            "Height",
                            "Weight",
                            "ProductType",
                            "Sku",
                            "Barcode",
                            "TrackInventory",
                            "OutOfStockRule"});
                table7.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", description),
                            string.Format("{0}", price),
                            string.Format("{0}", retail),
                            string.Format("{0}", cost),
                            string.Format("{0}", length),
                            string.Format("{0}", width),
                            string.Format("{0}", height),
                            string.Format("{0}", weight),
                            string.Format("{0}", productType),
                            string.Format("{0}", sku),
                            string.Format("{0}", barcode),
                            string.Format("{0}", trackInventory),
                            string.Format("{0}", outOfStockRule)});
#line 27
        testRunner.Given("Tom updates the following product:", ((string)(null)), table7, "Given ");
#line hidden
#line 30
        testRunner.When("Tom saves the updated product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
        testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UpdateProductsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UpdateProductsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
