// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.Features.Shipping
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateStoreProfileFeature : object, Xunit.IClassFixture<CreateStoreProfileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateStoreProfile.feature"
#line hidden
        
        public CreateStoreProfileFeature(CreateStoreProfileFeature.FixtureData fixtureData, DuxCommerce_Specifications_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Shipping", "Create Store Profile", "\tIn order to customize my online store\r\n\tAs a store admin\r\n\tI want to save my sto" +
                    "re profile", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create store profile and address")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Store Profile")]
        [Xunit.TraitAttribute("Description", "Create store profile and address")]
        [Xunit.InlineDataAttribute("MetricSystem", "Gram", "Centimeter", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Meter", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Foot", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Ounce", "Inch", new string[0])]
        public virtual void CreateStoreProfileAndAddress(string unitSystem, string weightUnit, string lengthUnit, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create store profile and address", null, tagsOfScenario, argumentsOfScenario);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table14.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 7
 testRunner.Given("Tom enters the following store profile:", ((string)(null)), table14, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table15.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 10
 testRunner.And("Tome enters the following store address:", ((string)(null)), table15, "And ");
#line hidden
#line 13
 testRunner.When("Tom saves the store profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table16.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 15
 testRunner.And("the store profile should be created as follow:", ((string)(null)), table16, "And ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table17.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 18
 testRunner.And("the store address should be created as follow:", ((string)(null)), table17, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create store profile - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Store Profile")]
        [Xunit.TraitAttribute("Description", "Create store profile - red path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Foot", "Invalid LengthUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Kilogram", "Inch", "Invalid LengthUnit", new string[0])]
        public virtual void CreateStoreProfile_RedPath(string unitSystem, string weightUnit, string lengthUnit, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create store profile - red path", null, tagsOfScenario, argumentsOfScenario);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table18.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 29
 testRunner.Given("Tom enters the following store profile:", ((string)(null)), table18, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table19.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 32
 testRunner.And("Tome enters the following store address:", ((string)(null)), table19, "And ");
#line hidden
#line 35
 testRunner.When("Tom saves the store profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create default shipping profile")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Store Profile")]
        [Xunit.TraitAttribute("Description", "Create default shipping profile")]
        public virtual void CreateDefaultShippingProfile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create default shipping profile", null, tagsOfScenario, argumentsOfScenario);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table20.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            "MetricSystem",
                            "Gram",
                            "Centimeter"});
#line 45
 testRunner.Given("Tom enters the following store profile:", ((string)(null)), table20, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table21.AddRow(new string[] {
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 48
 testRunner.And("Tome enters the following store address:", ((string)(null)), table21, "And ");
#line hidden
#line 51
 testRunner.When("Tom saves the store profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "IsDefault"});
                table22.AddRow(new string[] {
                            "Default Profile",
                            "True"});
#line 53
 testRunner.And("default shipping profile should be created as follow:", ((string)(null)), table22, "And ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode",
                            "IsDefault"});
                table23.AddRow(new string[] {
                            "1 Market Street",
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU",
                            "True"});
#line 56
 testRunner.And("shipping origin should be created as follow:", ((string)(null)), table23, "And ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table24.AddRow(new string[] {
                            "AU"});
#line 59
 testRunner.And("shipping zones should be created as follow:", ((string)(null)), table24, "And ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "CountryCode"});
                table25.AddRow(new string[] {
                            "AU"});
#line 62
 testRunner.And("shippig countries should be created as follow:", ((string)(null)), table25, "And ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "CountryCode",
                            "Name"});
                table26.AddRow(new string[] {
                            "AU",
                            "New South Wales"});
#line 65
 testRunner.And("shippig states should be created as follow:", ((string)(null)), table26, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateStoreProfileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateStoreProfileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
