// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.Features.Shipping
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UpdateStoreProfileFeature : object, Xunit.IClassFixture<UpdateStoreProfileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateStoreProfile.feature"
#line hidden
        
        public UpdateStoreProfileFeature(UpdateStoreProfileFeature.FixtureData fixtureData, DuxCommerce_Specifications_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Shipping", "Update Store Profile", "\tIn order to customize my online store\r\n\tAs a store admin\r\n\tI want to update my s" +
                    "tore profile", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "StoreName",
                        "ContactEmail",
                        "SenderEmail",
                        "BusinessName",
                        "PhoneNumber",
                        "TimeZoneId",
                        "UnitSystem",
                        "WeightUnit",
                        "LengthUnit"});
            table39.AddRow(new string[] {
                        "Deals365",
                        "c@gmail.com",
                        "s@gmail.com",
                        "Deals365 PTY",
                        "89457621",
                        "UTC",
                        "MetricSystem",
                        "Gram",
                        "Centimeter"});
#line 7
 testRunner.Given("Tom creates the following store profile:", ((string)(null)), table39, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "LastName",
                        "AddressLine1",
                        "AddressLine2",
                        "City",
                        "PostalCode",
                        "StateName",
                        "CountryCode"});
            table40.AddRow(new string[] {
                        "James",
                        "Harper",
                        "1 Market Street",
                        "",
                        "Sydney",
                        "2000",
                        "New South Wales",
                        "AU"});
#line 10
 testRunner.And("Tom creates the following store address:", ((string)(null)), table40, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update store profile - green path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update Store Profile")]
        [Xunit.TraitAttribute("Description", "Update store profile - green path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Meter", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Gram", "Centimeter", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Foot", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Ounce", "Inch", new string[0])]
        public virtual void UpdateStoreProfile_GreenPath(string unitSystem, string weightUnit, string lengthUnit, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update store profile - green path", null, tagsOfScenario, argumentsOfScenario);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table41.AddRow(new string[] {
                            "Deals360",
                            "contact@gmail.com",
                            "sender@gmail.com",
                            "Deals360 PTY",
                            "89457688",
                            "UTC+2",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 15
 testRunner.When("Tom enters the following store profile:", ((string)(null)), table41, "When ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table42.AddRow(new string[] {
                            "James",
                            "Harper",
                            "Unit 7",
                            "2 Market Street",
                            "Melbourne",
                            "3000",
                            "Victoria",
                            "AU"});
#line 18
 testRunner.And("Tom enters the following store address:", ((string)(null)), table42, "And ");
#line hidden
#line 21
 testRunner.And("Tom updates the store profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
 testRunner.Then("Tom should receive status codes OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table43.AddRow(new string[] {
                            "Deals360",
                            "contact@gmail.com",
                            "sender@gmail.com",
                            "Deals360 PTY",
                            "89457688",
                            "UTC+2",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 23
 testRunner.And("the store profile should be updated as follow:", ((string)(null)), table43, "And ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table44.AddRow(new string[] {
                            "James",
                            "Harper",
                            "Unit 7",
                            "2 Market Street",
                            "Melbourne",
                            "3000",
                            "Victoria",
                            "AU"});
#line 26
 testRunner.And("the store address should be updated as follow:", ((string)(null)), table44, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update store profile - red path")]
        [Xunit.TraitAttribute("FeatureTitle", "Update Store Profile")]
        [Xunit.TraitAttribute("Description", "Update store profile - red path")]
        [Xunit.InlineDataAttribute("MetricSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("MetricSystem", "Kilogram", "Foot", "Invalid LengthUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Pound", "Centimeter", "Invalid WeightUnit", new string[0])]
        [Xunit.InlineDataAttribute("ImperialSystem", "Kilogram", "Inch", "Invalid LengthUnit", new string[0])]
        public virtual void UpdateStoreProfile_RedPath(string unitSystem, string weightUnit, string lengthUnit, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UnitSystem", unitSystem);
            argumentsOfScenario.Add("WeightUnit", weightUnit);
            argumentsOfScenario.Add("LengthUnit", lengthUnit);
            argumentsOfScenario.Add("Comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update store profile - red path", null, tagsOfScenario, argumentsOfScenario);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "StoreName",
                            "ContactEmail",
                            "SenderEmail",
                            "BusinessName",
                            "PhoneNumber",
                            "TimeZoneId",
                            "UnitSystem",
                            "WeightUnit",
                            "LengthUnit"});
                table45.AddRow(new string[] {
                            "Deals365",
                            "c@gmail.com",
                            "s@gmail.com",
                            "Deals365 PTY",
                            "89457621",
                            "UTC",
                            string.Format("{0}", unitSystem),
                            string.Format("{0}", weightUnit),
                            string.Format("{0}", lengthUnit)});
#line 37
 testRunner.When("Tom enters the following store profile:", ((string)(null)), table45, "When ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table46.AddRow(new string[] {
                            "James",
                            "Harper",
                            "1 Market Street",
                            "",
                            "Sydney",
                            "2000",
                            "New South Wales",
                            "AU"});
#line 40
 testRunner.And("Tom enters the following store address:", ((string)(null)), table46, "And ");
#line hidden
#line 43
 testRunner.And("Tom updates the store profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UpdateStoreProfileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UpdateStoreProfileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
