// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuxCommerce.Specifications.Features.Checkout
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateShippingAddressFeature : object, Xunit.IClassFixture<CreateShippingAddressFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateShippingAddress.feature"
#line hidden
        
        public CreateShippingAddressFeature(CreateShippingAddressFeature.FixtureData fixtureData, DuxCommerce_Specifications_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Checkout", "Create Shipping Address", "\tIn order to get my products delivered\r\n\tAs an online shopper\r\n\tI want to enter m" +
                    "y shipping address during checkout", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Index",
                        "Name",
                        "Description",
                        "Price",
                        "Retail",
                        "Cost",
                        "Length",
                        "Width",
                        "Height",
                        "Weight",
                        "ProductType",
                        "Sku",
                        "Barcode",
                        "TrackInventory",
                        "OutOfStockRule"});
            table8.AddRow(new string[] {
                        "1",
                        "DDD",
                        "DDD Description",
                        "100",
                        "120",
                        "80",
                        "1",
                        "2",
                        "3",
                        "4",
                        "DigitalProduct",
                        "ddd-book",
                        "1234567890111",
                        "True",
                        "Remove"});
            table8.AddRow(new string[] {
                        "2",
                        "BDD",
                        "BDD Description",
                        "50",
                        "110",
                        "70",
                        "2",
                        "3",
                        "4",
                        "5",
                        "PhysicalProduct",
                        "bdd-book",
                        "1234567890222",
                        "False",
                        "ContinueSelling"});
            table8.AddRow(new string[] {
                        "3",
                        "TDD",
                        "TDD Description",
                        "80",
                        "100",
                        "60",
                        "3",
                        "4",
                        "5",
                        "6",
                        "DigitalProduct",
                        "tdd-book",
                        "1234567890333",
                        "True",
                        "StopSelling"});
#line 7
 testRunner.Given("the following products are already created:", ((string)(null)), table8, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create shipping address")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Shipping Address")]
        [Xunit.TraitAttribute("Description", "Create shipping address")]
        public virtual void CreateShippingAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create shipping address", null, tagsOfScenario, argumentsOfScenario);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product",
                            "Name",
                            "Quantity"});
                table9.AddRow(new string[] {
                            "1",
                            "DDD",
                            "4"});
                table9.AddRow(new string[] {
                            "2",
                            "BDD",
                            "8"});
#line 14
 testRunner.And("Amy adds the following products to her shopping cart:", ((string)(null)), table9, "And ");
#line hidden
#line 18
 testRunner.And("Amy enters the email address amy@gmail.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "AddressLine1",
                            "AddressLine2",
                            "City",
                            "PostalCode",
                            "StateName",
                            "CountryCode"});
                table10.AddRow(new string[] {
                            "James",
                            "Harper",
                            "Unit 7",
                            "2 Market Street",
                            "Melbourne",
                            "3000",
                            "Victoria",
                            "AU"});
#line 19
 testRunner.And("Amy enters the following shipping address", ((string)(null)), table10, "And ");
#line hidden
#line 22
 testRunner.When("Amy saves the shipping address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
 testRunner.Then("Tom should receive status codes BadRequest", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
 testRunner.Then("the shipping address should be created as expected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateShippingAddressFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateShippingAddressFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
